# -*- coding: utf-8 -*-
"""decisiontree cancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCb04C6VZfujHcZH5z86D3vj5oMeszGq
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
import numpy as np
df = pd.read_csv('Cancer_DS - Cancer_DS.csv')
x = df.drop('diagnosis', axis=1)
y = df['diagnosis']
print(df.head())
print(df.info())
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
clf = DecisionTreeClassifier(random_state=42)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
plt.figure(figsize=(15, 10))
plot_tree(clf, filled=True, feature_names=x.columns, class_names=df['diagnosis'].unique())
plt.show()
sample = [[12.67,15.12, 17.89, 103.6, 781, 0.0971, 0.1292, 0.09954, 0.06606, 0.1842, 0.06082, 0.5058, 0.9849, 3.564, 54.16, 0.005771, 0.04061, 0.02791, 0.01282, 0.02008,0.004144,20.42,27.28,136.5,1299,0.1396,0.5609,0.3965,0.181,0.3792,0.1048]]
pred = clf.predict(sample)
res = pred[0]
if res == 'B':
    print('Benign')
else:
    print('Malignant')