# -*- coding: utf-8 -*-
"""LAB1descriptive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfmMwQenTsx7oon6wmBzeh2N8dIwWO1u
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Creating a sample dataset
data = {'Age': [25, 30, 22, 35, 28, 22],
        'Salary': [50000, 60000, 45000, 70000, 55000, 60000]}

# 1. DataFrame(): Creating a DataFrame
df = pd.DataFrame(data)

"""creates a DataFrame."""

# 2. head()
print("First few rows of the DataFrame:")
print(df.head())

"""
Displays the first 5 rows of the DataFrame."""

# 3. tail()
print("\nLast few rows of the DataFrame:")
print(df.tail())

"""
Displays the last 5 rows of the DataFrame."""

# 4. count()
print("\nNumber of non-null observations in each column:")
print(df.count())

"""both 'Age' and 'Salary' have 6 non-null observations"""

# 5. sum()
print("\nSum of 'Salary' column:")
print(df['Salary'].sum())

"""Displays the sum of values in the 'Salary' column."""

# 6. mean()
print("\nMean of 'Age' column:")
print(df['Age'].mean())

"""It gives the average age of the dataset."""

# 7. median()
print("\nMedian of 'Salary' column:")
print(df['Salary'].median())

"""It provides the middle value of the salary data"""

# 8. mode()
print("\nMode of 'Age' column:")
print(df['Age'].mode())

"""It indicates the most common age in the dataset."""

# 9. std()
print("\nStandard Deviation of 'Salary' column:")
print(df['Salary'].std())

"""It measures the spread or variability of salaries."""

# 10. min()
print("\nMinimum value in 'Age' column:")
print(df['Age'].min())

"""It shows the youngest age in the dataset."""

# 11. max()
print("\nMaximum value in 'Salary' column:")
print(df['Salary'].max())

"""It provides the highest salary in the dataset."""

# 12. abs()
print("\nAbsolute values of 'Salary' column:")
print(df['Salary'].abs())

"""It ensures all salary values are positive."""

# 13. prod()
print("\nProduct of 'Age' column:")
print(df['Age'].prod())

"""It provides the product of ages"""

# 14. cumsum()
print("\nCumulative sum of 'Salary' column:")
print(df['Salary'].cumsum())

"""It shows how the total salary accumulates as moving through the dataset"""

# 15. cumprod()
print("\nCumulative product of 'Age' column:")
print(df['Age'].cumprod())

"""It demonstrates how the product accumulates as moving through the dataset."""

# 16. describe()
print("\nSummary of statistics for the DataFrame:")
print(df.describe())

"""function provides a summary of statistics for the entire DataFrame, including count, mean, std, min, and max for both 'Age' and 'Salary'."""