# -*- coding: utf-8 -*-
"""LAB8naivebayescancer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/123vKamBgpj564u2e_iuEHMrJcMX4o5nI
"""

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

data=pd.read_csv('/content/drive/MyDrive/dataset/Cancer_DS - Cancer_DS.csv')

data

#split the datas into features(x) and target(y)
X = data.drop(['id', 'diagnosis'], axis=1)
y = data['diagnosis']

# Split the dataset into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Naive Bayes classifier
clf = GaussianNB()

# Fit the classifier to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

y_pred

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')